--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayaka/Pictures/wallpaper/ders1cg7ng391.jpg"

-- Special
background="#13151b"
foreground="#c8cedf"
cursor="#c8cedf"

-- Colors
color0="#13151b"
color1="#5D6494"
color2="#9D6A8F"
color3="#738CAD"
color4="#A19B9D"
color5="#C5B9BD"
color6="#E6D2B1"
color7="#c8cedf"
color8="#8c909c"
color9="#5D6494"
color10="#9D6A8F"
color11="#738CAD"
color12="#A19B9D"
color13="#C5B9BD"
color14="#E6D2B1"
color15="#c8cedf"
