# Shell variables
# Generated by 'wal'
wallpaper='/home/ayaka/Pictures/wallpaper/ders1cg7ng391.jpg'

# Special
background='#13151b'
foreground='#c8cedf'
cursor='#c8cedf'

# Colors
color0='#13151b'
color1='#5D6494'
color2='#9D6A8F'
color3='#738CAD'
color4='#A19B9D'
color5='#C5B9BD'
color6='#E6D2B1'
color7='#c8cedf'
color8='#8c909c'
color9='#5D6494'
color10='#9D6A8F'
color11='#738CAD'
color12='#A19B9D'
color13='#C5B9BD'
color14='#E6D2B1'
color15='#c8cedf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
