--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayaka/wallpaper/ayaka-genshin-impact-art-1-4k-wallpaper-3840x2160-uhdpaper.com-976.1_a.jpg"

-- Special
background="#161415"
foreground="#e9e1e9"
cursor="#e9e1e9"

-- Colors
color0="#161415"
color1="#718DB1"
color2="#A193AA"
color3="#D59FAA"
color4="#A5ACCE"
color5="#E0AFD5"
color6="#C9D0D0"
color7="#e9e1e9"
color8="#a39da3"
color9="#718DB1"
color10="#A193AA"
color11="#D59FAA"
color12="#A5ACCE"
color13="#E0AFD5"
color14="#C9D0D0"
color15="#e9e1e9"
