--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/wallpaper/n2fAcSeR_4x.jpg"

-- Special
background="#261516"
foreground="#f6efdf"
cursor="#f6efdf"

-- Colors
color0="#261516"
color1="#E6D8AF"
color2="#F6D2B8"
color3="#B3B7D4"
color4="#CBBCD6"
color5="#D4D1DD"
color6="#F5D7CA"
color7="#f6efdf"
color8="#aca79c"
color9="#E6D8AF"
color10="#F6D2B8"
color11="#B3B7D4"
color12="#CBBCD6"
color13="#D4D1DD"
color14="#F5D7CA"
color15="#f6efdf"
