# Shell variables
# Generated by 'wal'
wallpaper='/home/ayaka/wallpaper/__kamisato_ayaka_genshin_impact_drawn_by_river_river_ga__5c3da3e249d084d07783f9dc91ee31cc.jpg'

# Special
background='#1a1315'
foreground='#dfcee4'
cursor='#dfcee4'

# Colors
color0='#1a1315'
color1='#966B9C'
color2='#E16C99'
color3='#748F81'
color4='#AA949B'
color5='#D3AC9F'
color6='#EFD5AB'
color7='#dfcee4'
color8='#9c909f'
color9='#966B9C'
color10='#E16C99'
color11='#748F81'
color12='#AA949B'
color13='#D3AC9F'
color14='#EFD5AB'
color15='#dfcee4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
