--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayaka/wallpaper/__kamisato_ayaka_genshin_impact_drawn_by_river_river_ga__5c3da3e249d084d07783f9dc91ee31cc.jpg"

-- Special
background="#1a1315"
foreground="#dfcee4"
cursor="#dfcee4"

-- Colors
color0="#1a1315"
color1="#966B9C"
color2="#E16C99"
color3="#748F81"
color4="#AA949B"
color5="#D3AC9F"
color6="#EFD5AB"
color7="#dfcee4"
color8="#9c909f"
color9="#966B9C"
color10="#E16C99"
color11="#748F81"
color12="#AA949B"
color13="#D3AC9F"
color14="#EFD5AB"
color15="#dfcee4"
