# Shell variables
# Generated by 'wal'
wallpaper='/home/rei/wallpaper/n2fAcSeR_4x.jpg'

# Special
background='#261516'
foreground='#f6efdf'
cursor='#f6efdf'

# Colors
color0='#261516'
color1='#E6D8AF'
color2='#F6D2B8'
color3='#B3B7D4'
color4='#CBBCD6'
color5='#D4D1DD'
color6='#F5D7CA'
color7='#f6efdf'
color8='#aca79c'
color9='#E6D8AF'
color10='#F6D2B8'
color11='#B3B7D4'
color12='#CBBCD6'
color13='#D4D1DD'
color14='#F5D7CA'
color15='#f6efdf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
