[Desktop Entry]
Type=X-GNOME-Metatheme
Name=ayayapoopie2.0
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=ayayapoopie2.0
GtkTheme=ayayapoopie2.0
IconTheme=ayayapoopie2.0
MetacityTheme=ayayapoopie2.0
